### ISSUE TITLE
2nd input field holds the past value for some reason?

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#102]
right after i supply Liquidity, it goes back to the Add Liquidity page
and the 2nd field holds the past value for some reason?

![image](https://user-images.githubusercontent.com/57817726/99597698-3c23eb00-29ad-11eb-8a11-7e3a36cd36d6.png)

**Comment by luzzif** [comment]
Should have been fixed in previous commit. Cannot see the described behavior in current builds.
