### ISSUE TITLE
Wrong percentage used for swap fee in message on adding liquidity

### ISSUE THREAD

**Issue by jpkcambridge** [levelkdev/dxswap-dapp#114]
![Screen Shot 2020-11-20 at 5 28 57 PM](https://user-images.githubusercontent.com/874683/99855972-fd7d6480-2b55-11eb-8775-d1f434cb8903.png)
 
When adding liquidity, the text box below says "By adding liquidity you'll earn 0.3% of all trades on this pair proportional to your share of the pool." instead of the current Swap Fee percentage

**Comment by 0xVenky** [comment]
Closing this issue, not relevant anymore.
