### ISSUE TITLE
Mobile navigation items cropped

### ISSUE THREAD

**Issue by nicoelzer** [levelkdev/dxswap-dapp#115]
![IMG_6590](https://user-images.githubusercontent.com/1383195/99880616-cc179e00-2c14-11eb-9462-f6df8d1ac570.PNG)

**Comment by zamli** [comment]
![image](https://user-images.githubusercontent.com/25611956/99925357-2a8c6b80-2d3e-11eb-837d-0945230399e5.png)
Put "charts" inside of the dots-menu.
