### ISSUE TITLE
Governance UI Mockup

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#123]
Start building up this mock up of governance
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=844%3A6037

**Comment by zamli** [comment]
Updated the first screen and added the rest of the governance screens.
One screen missing is "Create proposal screen". I will create this screen later on.

https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=882%3A1366

**Comment by zamli** [comment]
Show failed and passed proposals on the main pair screen and move them to proposal history after 24h.

![image](https://user-images.githubusercontent.com/25611956/100972892-de110f00-3539-11eb-9b82-821c84ea05a7.png)

**Comment by 0xVenky** [comment]
This has been moved to DxGovernance to work on, closing from Swapr board.
