### ISSUE TITLE
Governance Pairs

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#127]
Search feature will not work at start. We create it and hide it for later use.
If there is more than 3 rows of assets use a pagination. otherwise, hide the pagination.

https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=882%3A1420

**Comment by jsockchain** [comment]
@zamli I think this should be closed as well.

**Comment by zamli** [comment]
not yet. There is some changes. I'll update the issues

**Comment by 0xVenky** [comment]
This has been moved to DxGovernance to work on, closing from Swapr board.
