### ISSUE TITLE
Pool not showing up in Your Liquidity section

### ISSUE THREAD

**Issue by pimato** [levelkdev/dxswap-dapp#147]
<img width="2255" alt="Bildschirmfoto 2020-12-11 um 12 15 49" src="https://user-images.githubusercontent.com/5337809/101897373-bad60780-3baa-11eb-97eb-92e2bb1b05ba.png">

after a few refreshes it appeared:
<img width="721" alt="Bildschirmfoto 2020-12-11 um 12 17 51" src="https://user-images.githubusercontent.com/5337809/101897491-e9ec7900-3baa-11eb-9972-a34c6d8776f4.png">

**Comment by luzzif** [comment]
Should have been fixed recently. The issue was due to using Ethers default provider (which is heavily rate limited) to fetch both information about pairs and the token list.
