### ISSUE TITLE
Swap Fee displayed as .15% after creating a pair

### ISSUE THREAD

**Issue by jpkcambridge** [levelkdev/dxswap-dapp#150]
<img width="457" alt="Screen Shot 2020-12-10 at 6 04 13 PM" src="https://user-images.githubusercontent.com/874683/102052596-4a023b80-3db4-11eb-9e6c-97ed8a4d2155.png">

**Comment by calchulus** [comment]
in reserves.ts: there's something weird here in  line 58
     const swapFee =
        swapFees && swapFees[Pair.getAddress(token0, token1)] && swapFees[Pair.getAddress(token0, token1)].fee
          ? swapFees[Pair.getAddress(token0, token1)].fee
          : BigInt(15) 

Why is it bigInt(15) here? i feel like this might be since PAN isn't within in a set fee it somehow ends up here?
