### ISSUE TITLE
Swaps: Price impact not calculated as expected

### ISSUE THREAD

**Issue by nicoelzer** [levelkdev/dxswap-dapp#156]
As reported from @koeppelmann:

"just found a small bug: if I try to spend 1 ETH and next 20ETH on DXD the price moves significantly. However - the interfaces shows that the price impact is only 0.1% which is not true."

![Screen Shot 2020-12-19 at 16 34 11](https://user-images.githubusercontent.com/1383195/102694386-ec8d4500-4220-11eb-8172-dc318a8a3224.png)

![Screen Shot 2020-12-19 at 16 34 17](https://user-images.githubusercontent.com/1383195/102694388-eeef9f00-4220-11eb-924f-31456a0a09da.png)

**Comment by skyminert** [comment]
Note: https://github.com/levelkdev/dxswap-dapp/issues/104

It's not only calculating incorrectly.  It has some step cliff that is happening.  Meaning it drops off a cliff at some point.
