### ISSUE TITLE
https certificate "not secure" http request should redirect to https

### ISSUE THREAD

**Issue by pimato** [levelkdev/dxswap-dapp#157]
Hey guys,
getting:
<img width="474" alt="Bildschirmfoto 2020-12-19 um 19 27 11" src="https://user-images.githubusercontent.com/5337809/102696678-3d586a00-4230-11eb-8a68-0d87d073d491.png">

**Comment by pimato** [comment]
<img width="798" alt="Bildschirmfoto 2020-12-20 um 10 54 47" src="https://user-images.githubusercontent.com/5337809/102710322-cb286980-42b1-11eb-9e13-0872847087eb.png">

gone now :) , closing!

**Comment by pimato** [comment]
okay reopen this, as if I do:

http://swapr.eth.link -->
<img width="338" alt="Bildschirmfoto 2020-12-21 um 10 20 44" src="https://user-images.githubusercontent.com/5337809/102760696-350a4700-4376-11eb-8e33-4ea68a488879.png">

if I do:
https://swapr.eth.link -->
<img width="226" alt="Bildschirmfoto 2020-12-21 um 10 21 20" src="https://user-images.githubusercontent.com/5337809/102760743-4a7f7100-4376-11eb-97dd-9d358f783aed.png">

**Comment by 0xVenky** [comment]
Can be closed now. Redirecting to secured with http and https
