### ISSUE TITLE
Very small amount of ETH to DXD starts a Routing via USDC (why would this happen?)

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#162]
If you choose a small amount like 0.01 ETH to DXD, the routing goes through USDC and the "Price Impact" jumps to a much larger 2.46%

Once you increase the amount to about 0.05 ETH, the system then goes direct to DXD with 0.04% "Price impact"

Super weird.  What calculation/decision making is happening?

![image](https://user-images.githubusercontent.com/57817726/102792940-fff1fa80-435d-11eb-95df-0c8fb27082bf.png)

**Comment by skyminert** [comment]
For this same trial, Uniswap doesn't do this for me.

**Comment by 0xVenky** [comment]
I think this was closed with some of the earlier releases.
