### ISSUE TITLE
[Enhancement] Show the price of the token against ETH / USDT by default

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#167]
Right now, when a user opens a pair to trade, it lands up like this:
![image](https://user-images.githubusercontent.com/55109759/103384293-336b1c80-4af6-11eb-8861-5d615a893a2a.png)

And once the user enters the amount of ETH he is trading for, it shows up like this with "Price" added.
![image](https://user-images.githubusercontent.com/55109759/103384334-5695cc00-4af6-11eb-94e4-c923e2514e17.png)

1inch does it beautifully by showing the price by default and it actually saves a few clicks and types and provides a better user experience.

My proposal is to show the user the price of the token as 1 ETH = xyz <token> (or) xyz <token> = 0.00xyz ETH.

**Comment by zamli** [comment]
That's a great idea!
I think we can merge these two issues and do something.
https://github.com/levelkdev/dxswap-dapp/issues/124
I think I might need to design something smaller for this.

**Comment by 0xVenky** [comment]
Will be fixed with new Swap Box issue. Closing this.
