### ISSUE TITLE
[UI/UX] Add WETH to allowed token lists

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#169]
![image](https://user-images.githubusercontent.com/55109759/103437067-fcdef000-4c22-11eb-8ab4-64c052ab5fcb.png)

**Comment by KadenZipfel** [comment]
Where are you seeing this? Seems to work as expected for me

**Comment by 0xVenky** [comment]
Hey, Steps to reproduce:
Goto https://dxstats.eth.link/#/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 
Click on trade

It ends up in Swapr and shows this dialog.
