### ISSUE TITLE
Importing Pool function or hover note???

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#19]
Did we remove this function to import a pool? 
"Don't see a pool you joined? Import it."
If so, it is still in the hover note.
![image](https://user-images.githubusercontent.com/57817726/90717343-37438400-e264-11ea-9d4f-b342060f2e42.png)

**Comment by AugustoL** [comment]
Yes this message was left from the fork of uniswap, this was intended from users who had liquidity in V1 and didnt saw it in the new version. I removed the import option, going to change the hover note.
