### ISSUE TITLE
Token list picker

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#199]
Apart fomr the DxDao token lists, we should also be able to have token lists like

Uniswap Default
Coingecko Top 100

We should be able to fork what Uniswap has built for how token lists are displayed and have it for Swapr like below.

![image](https://user-images.githubusercontent.com/55109759/111081956-0f6c8400-8506-11eb-832b-2da2d7080bbb.png)

**Comment by zamli** [comment]
@mcabrams is working on this issue right now.
