### ISSUE TITLE
Trade detail structure not aligned

### ISSUE THREAD

**Issue by pimato** [levelkdev/dxswap-dapp#209]
If we have a grid structure, the items should be aligned correctly:
<img width="1495" alt="Bildschirmfoto 2021-03-30 um 09 57 04" src="https://user-images.githubusercontent.com/5337809/112954089-6006f280-913e-11eb-97a2-74171e1e7ab0.png">

**Comment by zamli** [comment]
Good eye.

**Comment by 0xVenky** [comment]
Closing this as part of housekeeping.
