### ISSUE TITLE
Switch asset circle button should be clickable everywhere

### ISSUE THREAD

**Issue by pimato** [levelkdev/dxswap-dapp#210]
Currently, only the small icon svg is the clickable part of the circle button. To improve the experience the button should be clickable as a whole:
<img width="106" alt="Bildschirmfoto 2021-03-30 um 09 58 25" src="https://user-images.githubusercontent.com/5337809/112954442-ac523280-913e-11eb-87f1-f1dcacc45ad6.png">

**Comment by 0xVenky** [comment]
Fixed and Closed
