### ISSUE TITLE
Allow users to switch networks only after beeing connected to a wallet

### ISSUE THREAD

**Issue by pimato** [levelkdev/dxswap-dapp#211]
<img width="419" alt="Bildschirmfoto 2021-03-30 um 10 04 55" src="https://user-images.githubusercontent.com/5337809/112955189-75305100-913f-11eb-9b42-1a5e0470355f.png">

Notes:
- We should not show the dropdown/network indicator here as the user did not picked the first step (wallet)
- Dropdown component has no padding

**Comment by 0xVenky** [comment]
Fixed and closed
