### ISSUE TITLE
Ensure settings  window can be closed by clicking anywhere on screen

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#216]
![image](https://user-images.githubusercontent.com/76129769/114233990-fbfcdf00-9932-11eb-81f7-57bcc1bf7487.png)

There appears to be a bug where the settings window will not close unless clicking the "X", when it is intended to close upon clicking anywhere elsewhere on the screen. In the above photo, the only way to close the window is VIA the circled X.

From Zett:

![image](https://user-images.githubusercontent.com/76129769/114234084-22bb1580-9933-11eb-9ffe-5b82cfdf4c61.png)

Tests done on Swapr.dev on 2021/04/09 at 1pm PST.

**Comment by luzzif** [comment]
Should be done on swapr.dev
