### ISSUE TITLE
Settings cog partially blocked by sunglass emoji in "Expert Mode"

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#217]
As shown in this GIF: ![image](https://gyazo.com/c3106de137414b3b1103ef0bfc9956ed.gif)

The sunglasses emoji blocks the functionality of the settings cog. Clicking does nothing, or will highlight the emoji. The cog still functions, but only at the top left corner.

Tests done on Swapr.dev on 2021/04/09 at 1pm PST.

**Comment by luzzif** [comment]
SHould be fixed on swapr.dev, thanks for reporting
