### ISSUE TITLE
Supply ETH without wrapping

### ISSUE THREAD

**Issue by powerschris** [levelkdev/dxswap-dapp#220]
I just tried to supply liquidity on Rinkeby to the DXD/WETH pool. I have DXD and ETH, but I can't use my ETH in the Add Liquidity page. Could Swapr automatically wrap my ETH to WETH, so I don't have to swap first and then add liquidity?
<img width="493" alt="Screen Shot 2021-04-12 at 2 53 29 PM" src="https://user-images.githubusercontent.com/47428627/114446211-facfea00-9b9e-11eb-96d7-7a1b85018216.png">

**Comment by 0xVenky** [comment]
@luzzif What do you think?  Should we auto wrap? It doesnt work like that on Uniswap right now though.

**Comment by KeenanLukeOM** [comment]
Just found out about wrapping/unwrapping inside of Swapr via inputting ETH -> WETH or VV. This looks and functions great. 

If automatically wrapping ETH is a possibility, I think it would be a valuable feature. If not, a simple window informing the user that they are able to wrap/unwrap ETH in Swapr should exist. This could look like a button or even just a information icon with an explanation on hover. In theory we could only display this to the user when they have either ETH or WETH inputted (as well of xdai or wxdai of course!)

**Comment by powerschris** [comment]
Just tried this again and it worked fine!
https://rinkeby.etherscan.io/tx/0x927fabbfafb9d102dbb07d444cad32b3f7cc2388fb42e2c761e508aa5a6a7461
