### ISSUE TITLE
Is Protocol fee correct on Rinkeby?

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#222]
Price
0.372361 DXD per WETH
Swap fee
0.25%
Protocol fee
0.00042%
Is the protocol fee correct?

**Comment by 0xVenky** [comment]
I also see that the Protocol fee is displayed as 0.00025% in xDAI. Federico thinks its a UI issue.

**Comment by luzzif** [comment]
I can confirm this is right. The protocol fee was apparently raised to `1÷~6=~0.16=~16%` on RInkeby.

**Comment by skyminert** [comment]
Wait - what are you saying here?

0.0025 * 0.16 = 0.0004   ????
