### ISSUE TITLE
Expecting to see pairs

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#223]
![image](https://user-images.githubusercontent.com/57817726/114642196-575b0400-9c88-11eb-87b2-74694ec5b583.png)

**Comment by 0xVenky** [comment]
Is there anything to be changed here @zamli If we are going to redesign the view entirely, I would suggest to close this. Lets keep this open only if we are trying to fix this view before Swapr 1.0

**Comment by zamli** [comment]
This view is going to be redesigned to show pairs first.
