### ISSUE TITLE
Choosing "WETH" shows me no pairs even though there are WETH pairs

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#225]
![image](https://user-images.githubusercontent.com/57817726/114642441-c6d0f380-9c88-11eb-8f4d-226e69816cfb.png)

**Comment by 0xVenky** [comment]
I think this is because of the Token A and Token B logic we have. We only do the filter based on Token A. So, even if we have a DXD - WETH pair, bwcause WETH is Token B here, we do not show this in the filter list.

**Comment by skyminert** [comment]
Yeah, seems that type of logic will cause that problem.  Will this scenario happen a lot?

Might have to change the logic?

**Comment by luzzif** [comment]
@0xVenky is right, it's exactly because of that logic. We maybe want to change it a bit @zamli?

**Comment by 0xVenky** [comment]
I would like to be able to search based on a token, regardless of Token0 or Token1. If this will not cause any performance problem in frontend and for fetching the data, we should implement search based on Token0 and Token1. :)

**Comment by powerschris** [comment]
I agree with @0xVenky 

The other thing that might be related is that searching for "ETH" returns all of the pairs. The url just goes back to the 'pools & rewards' page for all pairs. It would be nice if searching for ETH gave you the WETH pairs too.

**Comment by luzzif** [comment]
As of the latest build, I've removed ETH from the selectable assets in the list entirety because no pairs with raw ETH exist. I know it would be better to transparently handle ETH as WETH, but I think this still counts as an improvement.

**Comment by zamli** [comment]
Token A & Token B should be shown when choosing a token in the list. Can we filter on both?

**Comment by luzzif** [comment]
I think we can, but then we would have an inconsistency when the user selects grouped pairs from one of the cards presented to them in the initial screen. Those specifically group pairs by token 0. What should we do? When a user manually select a token from the modal, we should filter by both token0 and token1, while when a user selects a card we should filter only by token0?

**Comment by zamli** [comment]
I think we can always filter on token0 and token1. I see no cases where this doesnt work. token0+1 is just a technical thing and gives no meaning for us as long as the pools are 50%-50%.

**Comment by luzzif** [comment]
This has been fixed when switching to the new and improved pool view.
