### ISSUE TITLE
Clear up "Pool Size" and communicate what it is

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#229]
What is "Pool Size"?
Maybe an Info hover, to let me know what it is?
I don't know what it is
or what the number should be

![image](https://user-images.githubusercontent.com/57817726/114643084-d866cb00-9c89-11eb-97db-ae50306eb433.png)

**Comment by 0xVenky** [comment]
I noted this one as well. I think it would be great if we can display what is the equivalent value in Token A and Token B should be available (or) its equivalent USD value.

**Comment by zamli** [comment]
I'll redesign this so its clearer. For now I think we should launch It like this

**Comment by 0xVenky** [comment]
Closing this, we need new redesign for DIY farming page
