### ISSUE TITLE
Make it clear that you can't start a pool instantly or in the past (only in future)

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#231]
Otherwise you break it.

![image](https://user-images.githubusercontent.com/57817726/114643939-74dd9d00-9c8b-11eb-9cf2-b1d59b9cd338.png)

**Comment by 0xVenky** [comment]
We need better error handling. The error in the console log clearly mentions the start date is in the past. Maybe we have to display the message accordingly as well.

**Comment by skyminert** [comment]
Also, don't LET someone do this thing that you are not allowed to do.  Then you don't need any error display.

**Comment by luzzif** [comment]
This should have been fixed in the latest swapr.dev build. A start date in the past cannot be chosen anymore even when written explicitly in the text box, and also end date can never be prior to the start date or the current date.
