### ISSUE TITLE
Choose consistent Terminology

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#232]
Should we just use:

"Create Reward Pool" instead of "Create Liq. Mining"

We flip back and forth

![image](https://user-images.githubusercontent.com/57817726/114644089-b66e4800-9c8b-11eb-9001-99c3112558a5.png)

**Comment by zamli** [comment]
That's a good point. We should come up with a name.
options we have now.
a) Farming
b) Liquidity Mining
c) Rewards

I think all options has its pros and cons.

**Comment by 0xVenky** [comment]
Is this to be fixed? :)
