### ISSUE TITLE
Bug in the Total Reward # (until tried again)

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#233]
Look at the Reward Summary
the first time i tried, the Total Reward was showing totally wrong "10000000000000000"
even though i entered 100
then i changed pair and changed back
and it recognized the 100

![image](https://user-images.githubusercontent.com/57817726/114644248-fd5c3d80-9c8b-11eb-9947-c1390bda047c.png)

![image](https://user-images.githubusercontent.com/57817726/114644271-08af6900-9c8c-11eb-83ea-797cabaef0c4.png)

**Comment by luzzif** [comment]
Should be fixed and on swapr.dev. The issue was apparent when switching between reward tokens with a different number of decimals (the reward amount was not reinterpreted with the updated decimals amount).
