### ISSUE TITLE
Make the base pair token appear visually above the number of pairs.

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#237]
There appears to be a bit of confusion surrounding the pairs page, since it isn't immediately obvious you are selecting a token to get to its pairs. I think that having the "+#" of pools visually above the photo of the token detracts from the fact you are selecting that tokens pools.

Suggest either bringing the token image to the foreground, or centering the token image and having smaller (grey?) text below the name of the token show the number of pools. "2 pairs".

Personally I support centering the token image and placing an "X pairs" below the token name. This would to me best communicate that I am selecting a token to see its pairs, and would have the added benefit of communicating the number of pairs prior to selecting an asset (as we are currently trying to do).

![image](https://user-images.githubusercontent.com/76129769/114778169-5e861e80-9d29-11eb-94c2-4f01bc3e9045.png)
 
The red arrow indicates moving the "+2" to the background, or removing. The red circle indicating where we could instead indicate pair #'s.

**Comment by 0xVenky** [comment]
What do you think Zett? Should we make any changes or should I map this for the future iterations?

**Comment by zamli** [comment]
This screen will be changed into the new design. We keep it for now

**Comment by 0xVenky** [comment]
Closing this for now.
