### ISSUE TITLE
Introduce sorting to token pairs page

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#238]
When reaching a tokens pair page, it is unclear if there is any sorting logic - nor is there an option for the user to choose.

![image](https://user-images.githubusercontent.com/76129769/114778717-0f8cb900-9d2a-11eb-96b2-ba9da52284fa.png)

These should by default be sorted via liquidity size from left to right (unless we want incentivized pools to have priority regardless of liquidity size?), and have some indication of the size of the pool in the UI if possible. There should at minimum be a small explanatory "pairs are sorted by X logic". 

In theory, implementing a sorting choice could improve the UX as well.  "volume (24h and 7d)" "fees (24h and 7d)" among some others are potential considerations.

_Note: Testing on Rinkeby, I am unsure of current pool sizes and as a result there could be a sorting logic I am unaware of. Primary purpose of the issue is to ensure the user knows why they have been presented the pairs in the order they are shown._

**Comment by luzzif** [comment]
This should have been fixed while implementing the new pool and rewards page, which directly shows all the available pairs and sorts them by liquidity (which is also shown to the user).
