### ISSUE TITLE
Default "Reward pools" to "Active" unless the user has a position in the pair

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#239]
For “Reward Pools” found below an associated pool page, is it possible to default to “Active” if a wallet does not currently own a position? This feels like valuable information that you would expect to see by default when exploring pools. 

When I was exploring it became frustrating to have to select active each time, and could only imagine it would be more frustrating for a user exploring more than a few active pools.

![image](https://user-images.githubusercontent.com/76129769/114780146-dc4b2980-9d2b-11eb-9d65-10a52dc34f33.png)

_Pictured: Make "Active" the default instead of "Your positions", unless the user has a position._

**Comment by zamli** [comment]
Show Active first. remove "reward pools" title and Create titles like this
![image](https://user-images.githubusercontent.com/25611956/115400230-50347880-a1e9-11eb-8060-06ef80393a43.png)

**Comment by 0xVenky** [comment]
This can be closed.. :)
