### ISSUE TITLE
Be clear on the rate at which your rewards are updated in the UI

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#241]
The rate at which your reward updates appears to be 10-30 seconds? Perhaps it would be worth to either include something in the UI directly that states the rate, such as: (Rewards are constantly streaming, expect your balance to update every {X amount of time});

![image](https://user-images.githubusercontent.com/76129769/114783931-4d401080-9d2f-11eb-9e92-b54bc796c8c2.png)

_Pictured: Here could work?_

Another idea would be having the “rewards” roughly calculate and display a constant stream of the estimate between these updates. I am under the impression harvest.finance does this, and the actual number is only updated everyone once and a while. People love seeing a number move, especially their funds!

https://user-images.githubusercontent.com/76129769/114783846-2c77bb00-9d2f-11eb-8d62-e0f0cd01718c.mp4

**Comment by 0xVenky** [comment]
@zamli seems not to be a priority for 0.1 release I think, right? I added to v1 maybe there are some new designs that will fix this.

**Comment by 0xVenky** [comment]
Closing this, as we changed this as part of the redesign.
