### ISSUE TITLE
Partially withdrawing doesn't appear to be possible

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#242]
Context:

`You should be able to partially withdraw your LP and rewards.`

Withdrawing partial rewards worked as expected.  I do not appear to have the ability to withdraw LP tokens (presumably partially in this case). I only have the option to claim and withdraw, which exits the position entirely.

![image](https://user-images.githubusercontent.com/76129769/114784275-dce5bf00-9d2f-11eb-8113-7653da798e08.png)

_Pictured: I currently have staked LP tokens, I am able to "Claim rewards" and "Claim & Withdraw" to exit the position entirely. I do NOT have the option to "Withdraw `X/Y` LP", despite having an active position. As a result, I am unable to partially withdraw my LP._

**Comment by luzzif** [comment]
Can you retry? I think this might be linked to #243, which should now be fixed
