### ISSUE TITLE
LP tokens and rewards appear unclaimable after program has completed

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#243]
I tested on the WEENUS/WETH program on Rink.

I left my position open overnight, which was when the rewards program expired. Checking now, I do not appear to have the ability to claim my rewards, or withdraw my LP tokens. Holding the position past the closing date is the only thing I can think of that may attribute to this bug, please contact me directly for additional context if I did not describe the conditions correctly or if I am missing something vital.

![image](https://user-images.githubusercontent.com/76129769/114784953-cd1aaa80-9d30-11eb-99cf-5680d1d249ee.png)

_Pictured: I do not currently hold my pool tokens. The ability to "withdraw X/Y LP", "claim rewards", and "claim & withdraw" are all greyed out and unclickable. The UI still shows my position and associated rewards._

**Comment by luzzif** [comment]
Should be fixed here: 035f13551bb04fd0b784a065be1dba7f14131e9e.
I've also generally improved the behavior when the campaign has ended:

- Allow withdrawing on expired campaign
- Allow claiming rewards on expired campaign
- Allow exiting from a campaign only when claiming is allowed and there are at
