### ISSUE TITLE
Minor change to "Confirm staking" window

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#244]
Minor change for clarity:

Suggest the below window to be changed to “`X/Y` APPROVED”, to better indicate that the required action has been taken previously

![image](https://user-images.githubusercontent.com/76129769/114785347-6fd32900-9d31-11eb-9954-4174215495ae.png)

_Pictured: Button will be clickable and bright, but simply dims when the action is done. Suggest changing the text "Approve WEENUS/WETH" alongside the dim of the button, to affirm to the user they have approved the pair previously. In this case, it would be changed to “WEENUS/WETH APPROVED”._

**Comment by luzzif** [comment]
The dapp just got updated following your feedback on swapr.dev
