### ISSUE TITLE
WETH pairs not appearing in search for WETH pools

### ISSUE THREAD

**Issue by powerschris** [levelkdev/dxswap-dapp#245]
When I try to search for WETH in the 'Pools & Rewards' tab it shows 'No pairs yet' even though there is a DXD/WETH and a Xeenus/WETH pair. Searching by other tokens seems to work. When I tried to sort the pairs by just ETH, all pairs appeared.

https://swapr.dev/#/pools/0xc778417E063141139Fce010982780140Aa0cD5Ab 
<img width="854" alt="Screen Shot 2021-04-15 at 8 46 12 AM" src="https://user-images.githubusercontent.com/47428627/114871800-ac516400-9dc7-11eb-8465-413e31f89b65.png">

**Comment by 0xVenky** [comment]
Same as #225 ?

**Comment by luzzif** [comment]
Duplicate, closing.

**Comment by powerschris** [comment]
Yes - same thing. Should have checked through other issues
