### ISSUE TITLE
Unable to find position in expired reward pool

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#246]
This issue comes on the coattails of #243. Testing still done on Rinkeby, on the WEENUS/WETH pair.

In my attempt to check if the problem had been accounted for, I found out that I am no longer able to find my position that had expired. To confirm, I have NOT chosen to withdraw this position yet (since I was unable to previously) and my LP tokens are still (to the best of my knowledge) within the reward program.

![image](https://user-images.githubusercontent.com/76129769/114918014-728a5880-9ddb-11eb-9577-470ab3769749.png)

_Pictured^: The "My pairs" tab indicates I have one active position._

![image](https://user-images.githubusercontent.com/76129769/114918078-859d2880-9ddb-11eb-969e-e4d9ef6753fc.png)

_Pictured^: The My pairs window shows the expected pair that I previously had a position in._

![image](https://user-images.githubusercontent.com/76129769/114918153-9b125280-9ddb-11eb-881d-c8f2aaafa1c8.png)

_Pictured^: Clicking on the pair shows that I have no active position, and am therefore unable to retrieve my funds._

![image](https://user-images.githubusercontent.com/76129769/114918225-b2514000-9ddb-11eb-9551-57d702552d1c.png)

_Pictured^: The expected pool does not show under the expired tab either (it doesn't appear under active or upcoming either, but that is unexpected)._

**Comment by KeenanLukeOM** [comment]
Under the impression this is a result of redeploying the farming contracts. Please close this case provided it is the cause of the issue.

**Comment by 0xVenky** [comment]
This is probably because of the redeployment. Tested it again and I can find mine. Anyone else have this issue, else I suggest to close this one. :)
