### ISSUE TITLE
Minor change to liquidity mining creation

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#247]
Similar in context to issue #244.

When approving your reward token, the window greys out and becomes unclickable - but still implies the reward token may need to be approved.

Suggest changing the text to "Reward Token Approved" once approval has been made.

![image](https://user-images.githubusercontent.com/76129769/114921087-0578c200-9ddf-11eb-9916-8f158d02a5a6.png)

_Pictured: Text shows "Approve reward token" despite action already being taken, suggest changing to "Reward token approved"._

**Comment by KeenanLukeOM** [comment]
Totally glanced over the inflation of WEENUS, hope the high APY pool isn't an eye sore for the next two days. 😳

**Comment by 0xVenky** [comment]
Closing this as part of housekeeping.
