### ISSUE TITLE
Adding liquidity with miniscule amount crashes to white screen.

### ISSUE THREAD

**Issue by snufkin0x** [levelkdev/dxswap-dapp#253]
Tested on Swapr xDai v1.0.0-alpha.6 and Swapr.dev

When adding liquidity and one asset is basically dust, then pressing "Max" on it, the page goes completely white and you have to refresh to get back. What's more interesting, out of all 4 DXD liquidity pairs, it only crashes on 3 of them (does not crash on DXD/WXDAI pair).

![swapr3](https://user-images.githubusercontent.com/82238502/115968163-19d76000-a53f-11eb-98a7-61eb33d137bc.gif)

**Comment by luzzif** [comment]
Should be fixed on swapr.dev
