### ISSUE TITLE
After staking LP in rewards contract balance is not getting updated

### ISSUE THREAD

**Issue by pimato** [levelkdev/dxswap-dapp#254]
I just tested the rewards currently active and it seems like after I deposited `375.681642233709739559 LP tokens` from a total of `1375.681642233709739559 LP tokens` the UI is still showing me the total amount:
<img width="693" alt="Bildschirmfoto 2021-04-27 um 10 10 45" src="https://user-images.githubusercontent.com/5337809/116208105-d9dfcb00-a740-11eb-821f-1c44abd9c479.png">

Once the user deposits something, the total available balance should get updated!

after a refresh of the page:
<img width="699" alt="Bildschirmfoto 2021-04-27 um 10 13 12" src="https://user-images.githubusercontent.com/5337809/116208404-304d0980-a741-11eb-83b2-dd98dc2b9ac8.png">

**Comment by luzzif** [comment]
Great point, working on it

**Comment by luzzif** [comment]
Update: can't really replicate this. As soon as the staking tx is confirmed, I can see my stakable balance getting updated in real time. Can you please verify if the behavior is still there?
