### ISSUE TITLE
My Pairs not showing active staked pools

### ISSUE THREAD

**Issue by pimato** [levelkdev/dxswap-dapp#255]
So it looks like after I staked my LP for a specific pool to earn rewards it gets removed from the `My Pairs - Page` We should keep it there.

overview page, where you can see where I stake my LP tokens:
<img width="679" alt="Bildschirmfoto 2021-04-27 um 10 23 27" src="https://user-images.githubusercontent.com/5337809/116209933-adc54980-a742-11eb-825b-406fce4a8f54.png">

MY Pairs page:
<img width="683" alt="Bildschirmfoto 2021-04-27 um 10 23 30" src="https://user-images.githubusercontent.com/5337809/116209974-bae23880-a742-11eb-8ea8-99ac6c4d8a4d.png">

**Comment by luzzif** [comment]
Should be fixed on swapr.dev
