### ISSUE TITLE
Rewards Modal is not allowing me to deposit my LP because deposit available amount 0.00 LP

### ISSUE THREAD

**Issue by pimato** [levelkdev/dxswap-dapp#256]
I am providing liquidity for pool https://swapr.dev/#/pools/0xb90D6bec20993Be5d72A5ab353343f7a0281f158/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d

and it looks like I have `1578 LP tokens` but the deposit modal is showing `0`:
<img width="694" alt="Bildschirmfoto 2021-04-27 um 10 32 04" src="https://user-images.githubusercontent.com/5337809/116211157-d4d04b00-a743-11eb-9fe6-b847ce36e668.png">

**Comment by luzzif** [comment]
This happens because the staking pool is capped, and is full atm. When full, the deposit capability is blocked, both at the UI and at the smart contract level. We can talk a bit more about how to make this clearer on Keybase.
