### ISSUE TITLE
WXDAI/USDC pool link not working

### ISSUE THREAD

**Issue by powerschris** [levelkdev/dxswap-dapp#258]
Clicking on the WXDAI/USDC pool in the 'Pool and Rewards' and 'Pairs' and the link doesn't work.

Clicking on the WXDAI/USDC pool link simply reloads the Pools page like this:

https://user-images.githubusercontent.com/47428627/116249426-d21d2800-a73a-11eb-8224-dec123562c44.mov

If you are on the 'With Rewards' button the link takes you to the 'All Pairs' page but then clicking on the WXDAI/USDC pool in that page just reloads the 'All Pairs' page too. 

https://user-images.githubusercontent.com/47428627/116249760-20322b80-a73b-11eb-8d4d-214c772ef4b8.mov

This appears only to be the WXDAI/USDC pool (all of the other pools worked) and a simple refresh seemed to do the trick.

**Comment by luzzif** [comment]
Should be fixed on swapr.dev
