### ISSUE TITLE
Add support for Sushiswap on xDai

### ISSUE THREAD

**Issue by SoulRepo** [levelkdev/dxswap-dapp#261]
Sushiswap now has support for xDai tokens, which was added recently. It would be awesome to support Sushiswap's ability of exchanging xDai tokens for the xDai version of Swapr.

**Comment by 0xVenky** [comment]
Hi @SoulRepo , Seems like Sushiswap doesnt have any liquidity right now on XDAI. Once we see some liquidity, we will add it to our aggregator. Closing this issue for now.
