### ISSUE TITLE
Multichain linking potential issue

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/dxswap-dapp#262]
_This has been tested on Chromium, Firefox, and Edge(lol). I tested with and without metamask connection on Chromium, and without metamask for Firefox and Edge._

Directing to a multichain link for the first time opens as expected. (Using this in my testing: [https://swapr.dev/#/pools/0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d/0x1eF59bE0a990a9d6D8Af3FfAcc5D504A3e276843?chainId=100](https://swapr.dev/#/pools/0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d/0x1eF59bE0a990a9d6D8Af3FfAcc5D504A3e276843?chainId=100). In the provided example I am using Chromium without metamask, but as noted above this is reproducible in all cases for me - including using Metamask and switching to Ethereum from within.)

![image](https://user-images.githubusercontent.com/76129769/116757364-cd6aa500-a9c2-11eb-9a53-eeae40604205.png)

_Pictured: First time opening above link, no issues and presents the correct chain._

The problem seems to arise if you choose your network. In this example, I specifically choose the Ethereum network.

![image](https://user-images.githubusercontent.com/76129769/116757597-3baf6780-a9c3-11eb-9c41-13cd19cf5cb4.png)

_Pictured: In the above image, I manually choose the Ethereum network - bringing me back to the homepage of Swapr but on the Ethereum chain (?chainId=1)_

From here, I input the same [link as above](https://swapr.dev/#/pools/0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d/0x1eF59bE0a990a9d6D8Af3FfAcc5D504A3e276843?chainId=100), including (?chainId=100). As soon as I hit enter, the chainId switches to (?chainId=1) and I am left on an infinitely loading page.

https://user-images.githubusercontent.com/76129769/116758029-27b83580-a9c4-11eb-95b2-c735ec0554ae.mp4

_Pictured: Using the same link to view the pair (presumably sent to me externally/found on social media, etc), now ignores the chainId and loads infinitely._ 

This was reproduced with and without Metamask (switching my metamask network, and also switching the network directly in Swapr UI). Happy to provide additional context if needed!

**Comment by 0xVenky** [comment]
Closing this as this was fixed as part of Beta 4 or 5 perhaps.. :)
