### ISSUE TITLE
swapr.dev doesn't route USDC->WXDAI->DXD

### ISSUE THREAD

**Issue by snufkin0x** [levelkdev/dxswap-dapp#263]
Problem seems to be only on swapr.dev
![swaprdev](https://user-images.githubusercontent.com/82238502/116974896-79fc9d80-acc7-11eb-8d4b-c71252de38a4.png)

On swapr.eth.link all is fine.
![swapreth](https://user-images.githubusercontent.com/82238502/116974924-841e9c00-acc7-11eb-9851-fd585c4bf16e.png)

**Comment by snufkin0x** [comment]
My bad. Multihop was disabled. Maybe a reminder or an automatic switch-on would be good, if the price impact is too large.

**Comment by 0xVenky** [comment]
Closing this issue now. :) Thanks for reporting ! :)
