### ISSUE TITLE
Optimization: For Claiming Rewards once campaign is finished 

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#264]
For me, at the end of the farming campaign, I arrive to Swapr.  I feel it's quite hidden where my stake and rewards are.

On the "Pairs & Rewards" page, I do see the green "Staking" label.

Then you go into that pair, the only things letting you know that you have anything in there or rewards is the tiny little grey circle with "1" in it.  

If you miss that, you think you have nothing.  

![image](https://user-images.githubusercontent.com/57817726/116999282-66443d80-acad-11eb-9738-cd9e74dbd1b9.png)

One idea might be to keep using the green theme to make it easier to find your money and reward?

**Comment by 0xVenky** [comment]
Fixed as part of the new UX, released in Beta 8.
