### ISSUE TITLE
Arbitrum L1 - L2 Bridge MVP

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#270]

**Comment by zamli** [comment]
Updated design:
![image](https://user-images.githubusercontent.com/25611956/128367880-9a5a5abe-fe79-4a63-a8f1-f81ac8b23312.png)

https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=4049%3A24898

**Comment by 0xVenky** [comment]
Closing this one as the MVP just went Live with 8.1 release. The revised design with times will require a new card when we decide to work on it.
