### ISSUE TITLE
Bottom tab overrunning in iPhone X

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#285]
![image](https://user-images.githubusercontent.com/55109759/122827141-48c24600-d2e4-11eb-9596-ea410a85fab7.png)

Connect to a wallet and Metamask in Ethereum mainnet.
Device iPhone X

**Comment by zamli** [comment]
this will be fixed on new mobile navigation and the mobile fix for our swap box

**Comment by alexcherman** [comment]
@zamli I think it was solved when we remove settings button and word "gwei" here: https://github.com/levelkdev/dxswap-dapp/pull/299
