### ISSUE TITLE
Remove one of the settings icon

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#286]
![image](https://user-images.githubusercontent.com/55109759/122827376-8e7f0e80-d2e4-11eb-9575-f1bc3d4d79a6.png)

@zamli to confirm if the one near Multihop can be removed. :)

**Comment by 0xVenky** [comment]
![paste (4)](https://user-images.githubusercontent.com/55109759/122900681-2fa1af80-d34d-11eb-92db-f97e326eb053.png)

**Comment by zamli** [comment]
I think we can remove the settings button and also remove the word "gwei" from the gas selector.
![image](https://user-images.githubusercontent.com/25611956/122939180-b5385600-d373-11eb-958c-b1ca4975129f.png)

**Comment by alexcherman** [comment]
@zamli Can we close this issue. I think was solved
