### ISSUE TITLE
Should be using APR instead of APY(?)

### ISSUE THREAD

**Issue by KadenZipfel** [levelkdev/dxswap-dapp#287]
Haven't dug into the calculations but seems that APY would actually be much higher if compounded daily. Can someone confirm/deny my suspicion?

**Comment by 0xVenky** [comment]
Hey @KadenZipfel you are right :) we should be using APR instead. We are going to be reworking on the APY calculation that will basically be

`APY = APR (what we display) + daily reinvestment return + pool fee APY`

**Comment by 0xVenky** [comment]
Rename to APR is done. Closing this as we might want to discuss more about showing a APY
