### ISSUE TITLE
Add a disclaimer bar for swapr.dev

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#305]
Add a disclaimer bar only when visiting swapr.dev
![image](https://user-images.githubusercontent.com/25611956/125607718-873ba0c8-22dc-41cb-a4d1-f2809d39df27.png)
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=3883%3A41096

**Comment by alexcherman** [comment]
@zamli What tab should I open in Figma to find this component?

**Comment by zamli** [comment]
> @zamli What tab should I open in Figma to find this component?

i added a link that should automatically show you the right window.

**Comment by alexcherman** [comment]
Unfortunately, it shows me my current opened tab. But don't worry I found it.
