### ISSUE TITLE
Pagination tightning

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#307]
![image](https://user-images.githubusercontent.com/25611956/125821914-221c7f6c-a817-4a75-915e-f2bd1a44796e.png)
Change the pagination to this design.

https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=2842%3A1597

**Comment by alexcherman** [comment]
Should we close it? It was already merged.
