### ISSUE TITLE
Give spacing to loader

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#318]
![image](https://user-images.githubusercontent.com/25611956/129117683-d2f6379a-0bd9-4645-92f8-06413a09be1a.png)
Give this loader spacing 5px on left side

**Comment by alexcherman** [comment]
@zamli I think it was fixed by Federico 3 days ago here: https://github.com/levelkdev/dxswap-dapp/commit/c8ae85b4d167d1737a3952784a966423f32c05fc

**Comment by alexcherman** [comment]
Would you like to close this issue?
