### ISSUE TITLE
No eth on arbitrum Message

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#319]
![BG](https://user-images.githubusercontent.com/25611956/129455711-489706ef-0823-4dcf-8af2-bd9bf4c31dd3.png)
When eth is 0 on arbitrum show this message above the swap box
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=4205%3A25234

**Comment by zamli** [comment]
![BG](https://user-images.githubusercontent.com/25611956/129455711-489706ef-0823-4dcf-8af2-bd9bf4c31dd3.png)
When eth is 0 on arbitrum show this message above the swap box
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=4205%3A25234

**Comment by 0xVenky** [comment]
we need @zamli  to answer this, probably not relevant anymore with the new Swap Box and the new integrated landing page.

**Comment by zamli** [comment]
> we need @zamli  to answer this, probably not relevant anymore with the new Swap Box and the new integrated landing page. 

Not relevant anymore
