### ISSUE TITLE
Fees earned on DXstats seems incorrect

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#326]
On xDai DXstats:
https://dxstats.eth.link/#/account/0x561135d381a391d99d4c7e8a91ca666cd820d226

The Fees Earned (Cumulative) of $18,721 seems incorrect and too high

![image](https://user-images.githubusercontent.com/57817726/131265278-2a254933-1261-41e0-91ef-cc9815e18a96.png)

It's getting these Earned Fees in WETH and HAUS from somewhere

**Comment by adamazad** [comment]
@0xVenky any insight on this?

**Comment by 0xVenky** [comment]
Its fixed, but not released yet. :( We need to fix the dxstats repo soon, merging all the different PRs and then making a release in Github.

**Comment by 0xVenky** [comment]
Closing this for now.
