### ISSUE TITLE
ETH Balance rounding is incorrect

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#336]
On https://swapr.eth.link/#/swap?chainId=42161

The Balance is shown as: "1.90036"

When you click on the Balance to trade the Max, the field fills in with "1.8903673..."

So i guess it's rounding higher too early and incorrectly.  Should be more precise.  

![image](https://user-images.githubusercontent.com/57817726/131780117-cfd718f6-7019-4edd-b4b8-1e7341ed77d5.png)

**Comment by 0xVenky** [comment]
Hey @skyminert Can you try a different token than ETH, I think it is because there must be some ETH for the gasFee.

**Comment by 0xVenky** [comment]
Closing this now.
