### ISSUE TITLE
APY on pairs index page does not match APY on individual pair page

### ISSUE THREAD

**Issue by jpkcambridge** [levelkdev/dxswap-dapp#377]
<img width="225" alt="Screen Shot 2021-09-18 at 4 51 03 AM" src="https://user-images.githubusercontent.com/874683/133883103-4ce5e106-097d-4db7-85aa-3a7ac5ef7835.png">

<img width="262" alt="Screen Shot 2021-09-18 at 4 51 08 AM" src="https://user-images.githubusercontent.com/874683/133883113-7b87d586-9a51-4b8c-8467-f9e6484250e4.png">

The APY on the pairs index page appears to be incorrect.

**Comment by luzzif** [comment]
I think this has to either be closed or re-worded. The APY we show in the pair card is the maximum currently available among all the active campaigns on the pair in that moment. I.e. if there's a 30% camapign and someone creates a 1000% APY campaign, 1000% will be shown. If after staking, the 1000% campaign goes to 20% APY and the other stays at 30%, 30% will be shown. We might try to make it clearer that what's shown in the pair card is the maximum available APY, but other than that I don't see any issue here.
