### ISSUE TITLE
APY design, Top Right

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#386]

**Comment by zamli** [comment]
APY should be in the top right corner
![image.png](https://images.zenhubusercontent.com/61238acceb6eacff74da8a43/e0e4248f-c244-4e23-81f5-d91094e578e7)

See design:
![image.png](https://images.zenhubusercontent.com/61238acceb6eacff74da8a43/61dc7cae-0955-4aa3-87f9-e8dc8b3f6ffb)

**Comment by 0xVenky** [comment]
@alexcherman Is this something you can have a look?

**Comment by luzzif** [comment]
Just opened this PR: https://github.com/levelkdev/dxswap-dapp/pull/388
