### ISSUE TITLE
We need to update the text for LP fees

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#389]
We need to update this text to reflect what is for SWPR treasury and protocol fees based on the new SWPR token communication.

![image.png](https://images.zenhubusercontent.com/602e2f65345265247dd414cc/6b8b39a5-4543-4983-bcbb-acb34e66c959)

**Comment by KeenanLukeOM** [comment]
> Liquidity Provider Rewards

> On Swapr, all trades are subject to a fee, which is set to 0.5% by default but is adjustable by LPs. 90% of this fee is distributed directly to the LPs in accordance to their pool share, with the remaining 10% going to the SWPR fee share as a "protocol fee." 
> The Swapr Guild Treasury receives 70% of the SWPR fee share by default, while staked SWPR token holders receive 30%.

Fact check on using a 0.5% fee by default (I am under the impression 0.25% is correct for default, but was following my previous diagrams). Also fact check the fee share defaults.

**Comment by 0xVenky** [comment]
We decided to remove this section.
