### ISSUE TITLE
ENS avatar support

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#481]
Add ENS avatar support to swapr

https://medium.com/the-ethereum-name-service/nft-avatar-support-for-ens-profiles-bd4a5553f089

Fetch profile from ethereum and show it on ethereum, xdai and arbitrum.

**Comment by zamli** [comment]
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=5663%3A27362
![image.png](https://images.zenhubusercontent.com/61238acceb6eacff74da8a43/1d097e7a-ebcf-4844-be57-77c6f63f3773)

**Comment by zamli** [comment]
If wallet has no profile picture set, we show nothing just like how it looks like today

**Comment by zamli** [comment]
found a bug when picture is not square
![image.png](https://images.zenhubusercontent.com/61238acceb6eacff74da8a43/6c1fa0e4-1299-4f4f-87cb-1fd1eff8878d)
try mellody.eth

**Comment by zamli** [comment]
Current design is 29px height. The ENS image + the whole section is 32 px heigh.
![image.png](https://images.zenhubusercontent.com/61238acceb6eacff74da8a43/40c8f94d-39ee-4909-8580-f8a376c395b4)

**Comment by zamli** [comment]
![image.png](https://images.zenhubusercontent.com/61238acceb6eacff74da8a43/43f93a00-ab8a-459b-8640-04034057aad3)
There should be 3 px spacing/margin/padding here

**Comment by adamazad** [comment]
Closed via #488
