### ISSUE TITLE
"min. received" token logo isn't refreshing when one switches tokens in the swapping UI.

### ISSUE THREAD

**Issue by sacshin** [levelkdev/dxswap-dapp#495]
There is a small bug in the swap module's UI. When you use the ♻️ button to switch tokens, the logo of the "min. received" at the bottom sometimes stays as the old one as if you receive the one you're selling. But then if you enter a new amount and it refreshes and logo changes to the right one.
![swap](https://user-images.githubusercontent.com/55705611/144311594-e367f884-00d2-4cde-abc0-c2356a19db3f.png)

**Comment by 0xVenky** [comment]
I and Daniel discussed and this probably is a better implementation.
if the SwapBox has FROM(ESTIMATED), we should change text to MIN. COST
if the SwapBox has TO (ESTIMATED), we should keep the text to MIN RECEIVED

Reason is, once we implement this all the MIN RECEIVED becomes 1 XDAI for all the routers and is not a good comparison.

**Comment by denciu** [comment]
Closed by #581

**Comment by 0xVenky** [comment]
From the discussion we had on the Swapr weekly, lets go ahead and update the text from Min. Received to Max Sent if the estimation is on the From side.

When we encounter an AMM where this is not possible to display the right information, lets find a new way to solve this.

@zamli @denciu

**Comment by sacshin** [comment]
> From the discussion we had on the Swapr weekly, lets go ahead and update the text from Min. Received to Max Sent if the estimation is on the From side.
> 
> When we encounter an AMM where this is not possible to display the right information, lets find a new way to solve this.
> 
> @zamli @denciu
