### ISSUE TITLE
Create a crypto stats adapter for moneyprinter.info

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#534]

**Comment by natonnelier** [comment]
This is ready here: [https://github.com/natonnelier/cryptostats/blob/main/cryptostats.ts](https://github.com/natonnelier/cryptostats/blob/main/cryptostats.ts)

**Comment by 0xVenky** [comment]
Closing this ticket now as nothing more to be done frmo our side. Lets open a new ticket if more effort is required. :)
