### ISSUE TITLE
"Min. Received" wrong asset

### ISSUE THREAD

**Issue by jpkcambridge** [levelkdev/dxswap-dapp#536]
<img width="486" alt="Screen Shot 2022-01-10 at 2 16 26 PM" src="https://user-images.githubusercontent.com/874683/148825553-05fb2609-1abf-4739-a1ed-21c3f4832036.png">

When typing in a trade of 0.01 DAI to WETH, and then using the arrows in the trade widget to switch the direction of the trade, the min received numbers are still showing WETH instead of flipping to show DAI.

**Comment by jpkcambridge** [comment]
Previously reported in part by https://github.com/levelkdev/dxswap-dapp/issues/495

**Comment by 0xVenky** [comment]
Fixed as part of #495 and released in Beta 11
