### ISSUE TITLE
How do I "Remove Liquidity" from a pool?

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#55]
It usually works on Uniswap (but I wouldn't say always) so it must be doing something that is quite difficult.
Only if i choose "Add Liquidity" then manually choose the pair i want, can I see the Liquidity that i have already provided
and then this brings to next problem!

How to Remove Liquidity - have you guys tried that?

I have to:

Take this URL: https://gateway.pinata.cloud/ipfs/QmbkoS133ksbh9uv8ahsZePFKyZnqVLPUtFHxJnQQbHxNS/#/add/ETH/0x022E292b44B5a146F2e8ee36Ff44D3dd863C915c

replace "add" with "remove"

go to that URL
https://gateway.pinata.cloud/ipfs/QmbkoS133ksbh9uv8ahsZePFKyZnqVLPUtFHxJnQQbHxNS/#/remove/ETH/0x022E292b44B5a146F2e8ee36Ff44D3dd863C915c

then I can process a "Remove Liquidity" txn

I have been known to do this on Uniswap too!

so it is not a DXswap specific problem

I believe that @zett can fix this using Design

**Comment by AugustoL** [comment]
You dont see the remove button in the "manage" section of the pool?
I just removed 50% of my CHA/ANF pool,
![image](https://user-images.githubusercontent.com/7763867/97495899-f85a3a80-1946-11eb-86dc-e0e8444e48b7.png)

https://rinkeby.etherscan.io/tx/0x72074d21adb102892ad27e79c9793bfc4c392192172a3cc1b6a688b1526fa9b6

**Comment by skyminert** [comment]
Pools that I have provided liquidity to don't show up, so i have to manually enter token pairs, after clicking on "Add Liquidity".

Once you do this, there is no "Remove" option.

**Comment by AugustoL** [comment]
yes? thats weird! I am seeing the pairs that I provided liquidty for, I see the remove option when I click the manage dropdown in /pools

**Comment by luzzif** [comment]
Closing, should be fixed/not apply anymore.
