### ISSUE TITLE
Smaller ui/ux fixes for #531 Separation rewards pairs

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#556]
Here I will put the not as prioritized fixes for #531

**Comment by zamli** [comment]
Numbers pil is too smal for 2-3 numbers.
Make it look a rectangle. 
![image](https://user-images.githubusercontent.com/25611956/151365628-85dc55a7-b0aa-40fb-86f1-acfb89187415.png)

Here is the css for the one i tried locally
```
height: 16px;
    border: 1.75px solid rgb(240, 46, 81);
    color: rgb(240, 46, 81);
    border-radius: 4px;
    width: fit-content;
    padding: 0px 2px;
    font-size: 9px;
    font-weight: 500;
    font-family: 'montserrat';
```

**Comment by zamli** [comment]
![image](https://user-images.githubusercontent.com/25611956/151366046-4e6b4d6b-0fd4-4cc2-afb0-9f38093ea05a.png)
Icon for SWPR token missing from single token staking

**Comment by Mi-Lan** [comment]
> Numbers pil is too smal for 2-3 numbers. Make it look a rectangle. ![image](https://user-images.githubusercontent.com/25611956/151365628-85dc55a7-b0aa-40fb-86f1-acfb89187415.png)
> 
> Here is the css for the one i tried locally
> 
> ```
> height: 16px;
>     border: 1.75px solid rgb(240, 46, 81);
>     color: rgb(240, 46, 81);
>     border-radius: 4px;
>     width: fit-content;
>     padding: 0px 2px;
>     font-size: 9px;
>     font-weight: 500;
>     font-family: 'montserrat';
> ```

Should this be changed everywhere we use this bade? Since we also use it for bridge it will look like this ?
![Screenshot 2022-01-27 at 15 20 31](https://user-images.githubusercontent.com/33226956/151377190-4cc8c3d7-7380-41a0-83f8-4caa98670edd.png)

**Comment by zamli** [comment]
![image](https://user-images.githubusercontent.com/25611956/151366344-fa815d15-581b-452c-81d8-38000a004956.png)
"MY PAIRS change to "ALL"

**Comment by zamli** [comment]
> 

yes. lets do that

**Comment by zamli** [comment]
> > Numbers pil is too smal for 2-3 numbers. Make it look a rectangle. ![image](https://user-images.githubusercontent.com/25611956/151365628-85dc55a7-b0aa-40fb-86f1-acfb89187415.png)
> > Here is the css for the one i tried locally
> > ```
> > height: 16px;
> >     border: 1.75px solid rgb(240, 46, 81);
> >     color: rgb(240, 46, 81);
> >     border-radius: 4px;
> >     width: fit-content;
> >     padding: 0px 2px;
> >     font-size: 9px;
> >     font-weight: 500;
> >     font-family: 'montserrat';
> > ```
> 
> @zamli Should this be changed everywhere we use this bade? Since we also use it for bridge it will look like this ? ![Screenshot 2022-01-27 at 15 20 31](https://user-images.githubusercontent.com/33226956/151377190-4cc8c3d7-7380-41a0-83f8-4caa98670edd.png)

yeah lets do that!

**Comment by Mi-Lan** [comment]
> ![image](https://user-images.githubusercontent.com/25611956/151366344-fa815d15-581b-452c-81d8-38000a004956.png) "MY PAIRS change to "ALL"

What do you mean by this? Since default filter is ALL and when you toggle my pairs it switches to "MY PAIRS"

**Comment by zamli** [comment]
> > ![image](https://user-images.githubusercontent.com/25611956/151366344-fa815d15-581b-452c-81d8-38000a004956.png) "MY PAIRS change to "ALL"
> 
> @zamli What do you mean by this? Since default filter is ALL and when you toggle my pairs it switches to "MY PAIRS"

Answered through chat.

This should be the state when clicking "my pairs"
![paste (8)](https://user-images.githubusercontent.com/25611956/151393858-52a34d02-0ff7-4a53-8a75-cb47d7a3580f.png)

**Comment by Mi-Lan** [comment]
@zamli i pushed all those changes
