### ISSUE TITLE
Searching for HOPR doesnt work in LP pair under Rewards

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#586]

**Comment by kingalg** [comment]
I confirm - it's fixed with [https://github.com/levelkdev/dxswap-dapp/pull/606](url)
![Screenshot 2022-02-02 at 11 55 02](https://user-images.githubusercontent.com/68909168/152140687-163b3b5c-f445-4cb5-804a-f63c02f281ab.png)
