### ISSUE TITLE
Rectangular loaders for the Active and Expired

### ISSUE THREAD

**Issue by Mi-Lan** [levelkdev/dxswap-dapp#592]
Currently this is how loaders look:
![Screenshot 2022-01-28 at 13 31 40](https://user-images.githubusercontent.com/33226956/151547375-e7b8b223-bd61-47a3-91ef-f58747fd18c8.png)
Since update to the styling number of active/expired campaigns they are rectangular :
![Screenshot 2022-01-28 at 13 32 34](https://user-images.githubusercontent.com/33226956/151547477-2a9a1b6f-fdf9-42bf-add2-5a5b6fcaaef0.png)

**Comment by Adarsh-Raj-Jaiswal** [comment]
how may i help ?
