### ISSUE TITLE
single token staking modal shows I still have a stake even after I unstake

### ISSUE THREAD

**Issue by sacshin** [levelkdev/dxswap-dapp#597]
After I un-stake from the single-sided campaign, the UI still shows that I have stake to un-stake.
When I click in the top right corner, and in the farm view, it shows as if I am still staked, but when I go inside the campaign it correctly shows 0.
![single-sided](https://user-images.githubusercontent.com/55705611/151638497-87a732f4-e37a-4f6c-bd89-1de8d78d1198.png)

**Comment by Mi-Lan** [comment]
The issue here is the subgraph not updating fast enough...Only workaround I see is to fetch this data straight from contract like we do for rewards section

**Comment by kingalg** [comment]
I've staked and unstaked several times (in the version from [https://github.com/levelkdev/dxswap-dapp/pull/605](url) and all mentioned views update quite fast so I would say that this solution solved the problem.
