### ISSUE TITLE
liquidity and stake not detected

### ISSUE THREAD

**Issue by sacshin** [levelkdev/dxswap-dapp#599]
There is $2k liquidity provided to the SWPR/xDAI pair pool, and LP tokens are staked in the farming campaign, but selecting 'my pairs' doesn't show the pair. Going into the pair the liquidity isn't accounted and the farm card dosen't indicate 'staked'. Clicking on the card and going inside the farm page allows me to see my stake, claim rewards, unstake...
![farm card](https://user-images.githubusercontent.com/55705611/151719787-b8bb7d7a-f7bf-44a7-8c2c-3d8e113f677d.png)
![Liquidity not accounted for](https://user-images.githubusercontent.com/55705611/151719639-81a069de-e38f-4527-a348-484a05fc9350.PNG)

**Comment by Mi-Lan** [comment]
this is temporary issue with subgraph not being synced I don't see better solution on the front-end side of things
![Screenshot 2022-01-31 at 20 10 21](https://user-images.githubusercontent.com/33226956/151857064-fbfb3f3d-867c-45f4-aab0-14b15d72abe5.png)

**Comment by 0xVenky** [comment]
This will be closed based on the PR #605
