### ISSUE TITLE
For multi rewards, we need to add margin and padding to Rewards and remaining column

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#614]
Hey, we might soon start to have campaigns that have more than 2 rewards. Would be good to take a look at this view and see if we can increase the margin and padding or a redesign perhaps?

![image](https://user-images.githubusercontent.com/55109759/152417372-c88a09b9-8e10-4b77-987f-b4d051e48266.png)

**Comment by zamli** [comment]
Let's add 2 px more padding between the reward lines(vertical). That should be enough
