### ISSUE TITLE
Last page of pairs pagination is empty

### ISSUE THREAD

**Issue by adamazad** [levelkdev/dxswap-dapp#617]
Go to the last page of Beta 10. The page is empty.
![image](https://user-images.githubusercontent.com/1926216/152702936-756e7fee-ca05-4638-87ac-10d693b85c35.png)

**Comment by berteotti** [comment]
Is this bug still reproducible? I couldn't catch it in the develop branch. The UI is different from this screenshot, maybe it was already fixed.

**Comment by adamazad** [comment]
I tested this on the Beta 10 tag. Seems to be gone now. We can close this for now.
