### ISSUE TITLE
MOVR - implement returning bridge lists with routes from omnibridge 

### ISSUE THREAD

**Issue by denciu** [levelkdev/dxswap-dapp#691]
When validation passes, compute which bridges are available and include fetched routes from socket/movr. This method should be asynchronous and return some thing like this:

```ts
interface AvailableBridges {
[bridgeId: BridgeList]: {
    name: string
    errors: {
      severity: SomeSeverities,
      message: string
    }
    routes?: {
      gas?: string
      fee?: string
      estimatedTime?: number
     otherPropsFromMovr: any
    },
    gas?: string
    fee?: string
    estimatedTime?: number
  }}
```

Draft implementation:
 - filter supported bridges by chain
- check if token is on the list
- Omnibridge implements getSupportedBridges method:
  + calls getBridgingMetadata for supportedBridges that returns gas/fee/time/healthStatus/routes

**Comment by mix1o** [comment]
#725 Closed by #715
