### ISSUE TITLE
MOVR - approve/triggerCollect/Collect/Validate/triggerBridging implementation

### ISSUE THREAD

**Issue by denciu** [levelkdev/dxswap-dapp#694]
General overview on how it works:
0. [Service healthcheck](https://backend.movr.network/v2/swagger/#/Server/AppController_getHealth) - we're doing it on getting available bridges after validation
1. [Fetch supported chains](https://backend.movr.network/v2/swagger/#/Supported/SupportedController_getAllSupportedRoutes) - we are omitting it because we got it from SDK
2. After we got from & to chain id we fetch token lists: [from](https://backend.movr.network/v2/swagger/#/Token%20Lists/TokenListController_getfromTokenList) & [to](https://backend.movr.network/v2/swagger/#/Token%20Lists/TokenListController_getToTokenList)
3. [Fetch available routes](https://backend.movr.network/v2/swagger/#/Quote/QuoteController_getQuote)
4. [Start building tx](https://backend.movr.network/v2/swagger/#/Server/AppController_getSingleTx). In return we receive [data required for approval](https://backend.movr.network/v2/swagger/#/Approvals/ApproveController_fetchApprovalsCalldata) & txData to sign and bridge.
- do we need to use it or approve manually?
5. While buildiing tx we [check allowance](https://backend.movr.network/v2/swagger/#/Approvals/ApproveController_fetchApprovals)
- do we need to use it or check manually?

1. Approve
- [ ] implement [approve](https://backend.movr.network/v2/swagger/#/Approvals/ApproveController_fetchApprovalsCalldata) method in MovrBridge class.
- [ ] add activeRouteId to common store, set it when bridge implements routes so it is available for allowance validation later on.
- [ ] all routes will be kept in store under movr
- [ ] sign transaction manually

2. TriggerCollect/Collect - to our best knowledge in singleTx model of Socket there is no collect step therefore this will be void  function.

3. Validate
On validation trigger buildTx and run check-allowance. Push buildTx result along with approvalDetails.

4. triggerBridging
Once we got approval and txData from buildTx we need to sign txData manually and send it.

**Comment by mix1o** [comment]
Closed by #704
