### ISSUE TITLE
Farming pill text to green

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#741]
![image.png](https://images.zenhubusercontent.com/61238acceb6eacff74da8a43/1f0b796f-b109-4351-a9b5-1d775160a3d3)
Turn the text from white to green. Add additional space between the icon and the text.

The design.
![image.png](https://images.zenhubusercontent.com/61238acceb6eacff74da8a43/f151ba0f-3249-47fb-b096-71b39f1c627d)
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=5843%3A127749

**Comment by Mi-Lan** [comment]
@zamli This has been addressed already and fixed with this commit https://github.com/levelkdev/dxswap-dapp/commit/9e4e522866f1b78a7a41cde3d63a7cf39e09e62a
